### ISSUE TITLE
Apple Health compatibility

### ISSUE THREAD

**Issue by xan-m** [InfiniTimeOrg/InfiniLink#12]
Is this something people are interested in? I haven't implemented it yet because of 1) Apple's, well, dubious decisions lately have rubbed me the wrong way, so I'm wary of adding too many Apple-based features, 2) I personally don't think the HRM measurements are accurate or frequent enough to offer any meaningful health data, and 3) step count is not yet available over BLE, so you'd basically _only_ be syncing heart rate data.

If people are interested in syncing with Apple Health, I can try to implement it as a switchable service, so that people aren't forced to use it if they're not interested. 

Let me know what you think!

**Comment by ocdtrekkie** [comment]
I definitely would rather retain my own data than give it to Apple, but I can imagine some would want the option.

**Comment by calvellido** [comment]
Once step count is available to obtain over BLE, I think it might be an interesting option to have.

**Comment by bhibb** [comment]
Just chiming in here to say I'm not interested in syncing any data to Apple. Sure, you say, but then why do you use an iPhone if you're worried about sharing data? Well to that I say: I'm just waiting for my PinePhone to become daily driver ready! That, and work with the cellphone bands in my area (doesn't work with my carrier Verizon).

**Comment by xan-m** [comment]
@bhibb I'm in the exact same boat as you! I've got an iPhone that works today, so that's what I'm working on. Thanks for weighing in!

**Comment by computergeek125** [comment]
I understand the concerns many have with "publishing" this data to a company.  For those that don't mind Apple having some data, is it possible to only request access to the health information once the user opts-in to it?  That way if the user didn't opt in, it didn't even try to talk to the Apple system

**Comment by xan-m** [comment]
Yeah I would implement it as a switch in the app to activate it. Also iOS will also ask for permissions to Apple health, so it should be pretty hard to accidentally share data with Apple. It should be completely opt-in. That’s the main reason I’m considering it at all!

**Comment by generalsmithers** [comment]
Being able to sync data with Apple would be what makes the pinetime useful for me, since my workplace wellness program will only count steps from approved services, if which Apple is one

**Comment by xan-m** [comment]
That is a strong case for adding Apple Health support! Thank you for sharing that.

**Comment by ItzSwirlz** [comment]
Can agree with Step count. Sync it (ish) with Apple (if the phone detects a step and the watch doesn't update it)

**Comment by VelocityDesign** [comment]
Heyo, OrbitalDev here.
I think this would be great to have. Although I'm planning to switch to android again soon, its always nice to help out people with open source when possible.

The main use case for this feature could be the fact that the health app can send data to physicians. This seems like it would be very helpful and save a bit of headache with sending and exporting the graphs from the app.

**Comment by but-whythough** [comment]
Love the project and had a few thoughts about datasharing. I like the idea of choosing specific items if data to share with apple say step count, but not heart rate, in a toggle on off format so it is it is clear what you are sharing and how to stop sharing with wanted.

**Comment by dwt** [comment]
I would love syncing to apple health - because apple health data completely stays on my devices and is in no way shared with apple or any company. The only other smartwatch that I'm aware of that can do this is the Apple Watch. Which sucks, because price and battery life.

So yes, having another option to get a privacy preserving way to to get at my heart rate would be much appreciated.

**Comment by K4LCIFER** [comment]
I'd love this as well!

**Comment by ItzSwirlz** [comment]
Is this possible using Apple's HealthKit? I don't think this would require a proprietary service https://developer.apple.com/documentation/healthkit

**Comment by liamcharger** [comment]
This issue has been closed because Apple Health/HealthKit has been integrated.

**Comment by cyberneel** [comment]
@liamcharger I have the latest 1.1-beta IPA sideloaded on my phone and can't seem to find the setting to send data to the health app. Do you know how I can do this?

**Comment by liamcharger** [comment]
@cyberneel there isn't a manual trigger, it should happen automatically. 

I'll implement a trigger soon so if the permissions sheet doesn't open automatically after a reopen of the app or a restart of your iPhone, you can still access it.

**Comment by cyberneel** [comment]
I thi

> @cyberneel there isn't a manual trigger, it should happen automatically.
> 
> I'll implement a trigger soon so if the permissions sheet doesn't open automatically after a reopen of the app or a restart of your iPhone, you can still access it.

Maybe something isn't working as expected because I have a free developer account. Is it possible for you to push it to the App Store with proper entitlements or testflight?

**Comment by liamcharger** [comment]
I'll be pushing a new build as soon as I can, I'm still waiting on a license agreement to signed, and then I'll be able to.
