### ISSUE TITLE
Watch freezes and reboots after interacting with external resources

### ISSUE THREAD

**Issue by liamcharger** [InfiniTimeOrg/InfiniLink#122]
When uploading or deleting files on my PineTime's FS and then saving a setting on my watch, it will freeze and reboot. I'm investigating this issue, but I wanted to give you a heads up, @JenJell. 

The issue doesn't appear to occur when reading settings from the watch, leading me to believe the issue's with the LS function, as it doesn't freeze when updating external resources. There's also the possibility that it has something to do with the way it's used in my external resources file explorer implementation.

**Comment by JenJell** [comment]
That is strange, everything should be implement directly according to the documentation. Maybe two request are being sent to the watch at ones? Anyway, I will look into the problem myself as well.

**Comment by liamcharger** [comment]
It could also be an issue with InfiniTime, so I'm going to open an issue there, just in case.

**Comment by JenJell** [comment]
@liamcharger, after looking into it, the problem seems to appear when a setting is changed in the pinetime following the execution of the LS command and the FS directory has changed. I have triple checked the InfiniLink code, but I haven’t been able to identify any potential causes for this problem. Therefore, it’s plausible that the issue might reside within InfiniTime itself.

**Comment by liamcharger** [comment]
@JenJell I was beginning to think the same thing, and I was also seeing some recently opened issues in the InfiniTime repo about freezes, so I'm going to open an issue there, and then I'll link it here to keep you updated.

**Comment by liamcharger** [comment]
Issue opened [here](https://github.com/InfiniTimeOrg/InfiniTime/issues/2021).

**Comment by liamcharger** [comment]
I'm going to close the issue in this repository as it isn't specific to InfiniLink. There is still an issue open in the InfiniTime repository [here](https://github.com/InfiniTimeOrg/InfiniTime/issues/2021).
