### ISSUE TITLE
Mac app?

### ISSUE THREAD

**Issue by Xorger** [InfiniTimeOrg/InfiniLink#129]
Hey! Was wondering if it would be possible to make a native mac port for intel macs, as there aren't any mac companion apps ATM

I completely understand if this isn't feasable, but it's still something that would be nice as this would remove some of the dependencies for phones

**Comment by liamcharger** [comment]
Hi @Xorger!

I just opened a PR that introduces support for Intel Macs, and I'm working on getting a compiled version uploaded to TestFlight/the App Store. I'll comment on this issue again when I do!

**Comment by Xorger** [comment]
Cool! thanks so much! Just asking, will a .dmg/.zip for the app be distributed for download?

**Comment by liamcharger** [comment]
Yes, I'll try to remember to add a .dmg/.zip when I create the next release! 😜

**Comment by liamcharger** [comment]
The macOS version is available on TestFlight.

**Comment by Xorger** [comment]
Great! Sorry I Couldn't respond earlier, I was pretty busy.
