### ISSUE TITLE
Weather is incorrect

### ISSUE THREAD

**Issue by minacode** [InfiniTimeOrg/InfiniLink#134]
Apples Weather app says it's 26 degrees (which is probably true), but InfiniLink and the watch show 17 degrees (which is not true).

All software should be up to date. I am running my own branch which adds a calculator on top of the current main of InfiniTime, but that should not interfere which the weather.

**Comment by liamcharger** [comment]
Hi @minacode!

The weather is fetched using NWS (if you're in the US) and the WeatherAPI API anywhere else. I've been hearing reports of incorrect weather (especially weather from WeatherAPI), so I may end up switching to WeatherKit, which would fetch data from Apple and should be correct.

So in summary, this is an issue with the weather providers, not InfiniLink. I'll look into possibly switching to WeatherKit, though, so thank you for reporting this!

**Comment by minacode** [comment]
Thank you for responding so quick and the work you do. I live in Germany, so I guess it's the APIs fault.

**Comment by minacode** [comment]
A little update on this: seems like I had a wrong location setting, because it does work now. But I only get one day off data. Is this to be expected from the current implementation?

> I'll look into possibly switching to WeatherKit

This would be the natural choice on iOS, right?

**Comment by liamcharger** [comment]
No, it's not...

I can't really do anything about it in the version you're running since it's WeatherAPI's fault, but I have implemented WeatherKit in another branch, which will be available when I'm finished with the rest of its features.

**Comment by minacode** [comment]
Thank you!
