### ISSUE TITLE
Filter zeros in heart rate

### ISSUE THREAD

**Issue by minacode** [InfiniTimeOrg/InfiniLink#136]
I have zeros in my Apple Health heart rate data. Could you add a filter for them?

**Comment by liamcharger** [comment]
Sure! I thought I had added a guard for them but maybe I didn't...I'll double check. Thanks for letting me know!

**Comment by minacode** [comment]
It's almost always the last value.

**Comment by liamcharger** [comment]
This issue will be fixed in the next available build.
