### ISSUE TITLE
[Feature Request] Display battery in built in widget

### ISSUE THREAD

**Issue by coffandro** [InfiniTimeOrg/InfiniLink#138]
There's a nice built in widget to IOS that displays the battery level of the phone and accessories, I would love it if this also displayed the battery level of the pinetime

**Comment by liamcharger** [comment]
update: ever since ANCS was implemented (note: the pr hasn't been merged yet) the PineTime is displayed the battery widget. You can see [this InfiniTime issue](https://github.com/InfiniTimeOrg/InfiniTime/issues/2177) for more context
