### ISSUE TITLE
TestFlight link doesn’t work

### ISSUE THREAD

**Issue by piajesse** [InfiniTimeOrg/InfiniLink#140]
When you click on the TestFlight link in README.md, it opens up TestFlight with the message “This beta isn’t accepting any new testers right now.”

**Comment by liamcharger** [comment]
Hi @piajesse!

This is happening because the most recent TestFlight build has expired.

A new one is coming, but it's taking a bit longer because Apple made some changes that require action from the Pine64 Developer Account Holder.

**Comment by LiberalArtist** [comment]
I was confused by this, too: maybe this issue should be reopened until it is resolved?

**Comment by liamcharger** [comment]
I think I'll just remove the link from the README until a new build is available, sorry for the confusion!

**Comment by liamcharger** [comment]
I just pushed a new build, so the app is now available in TestFlight again!
