### ISSUE TITLE
Graph infobox issues

### ISSUE THREAD

**Issue by xan-m** [InfiniTimeOrg/InfiniLink#26]
Converting a todo item to an issue. Got some TestFlight feedback that it's frustrating that the info box disappears when you lift your finger from the graph, and I agree.

However, in order to make the info box persistent, I'll need to either choose a new graphing package, or fork the one I'm using and modify it. The variables that would give me the data to present it myself are declared as internal, and thus can't be accessed at run time from outside of the class. The info box itself is implemented only to be active 

I'd rather focus on bigger issues right now, so I'm creating this issue to dog ear this side project.

**Comment by hellojaccc** [comment]
It'd be nice to see date in infobox since it supports hour/day/week graph

**Comment by xan-m** [comment]
I will see what I can do @hellojaccc
