### ISSUE TITLE
Configurable option to support time-based graphing as opposed to index-based graphing

### ISSUE THREAD

**Issue by computergeek125** [InfiniTimeOrg/InfiniLink#40]
(Possibly related to #26)

In its current state, the app will show the graphs of HR and battery.  Scrolling over the graph, there appear to be time jumps that aren't accounted for with "blank" data where the watch was either disconnected from the phone or not recording for whatever reason.  Notably, I can see a jump from last night when my phone died and disconnected from the watch.  

These don't show any kind of relative time scale between jumps, which can make 1am and 7am appear right next to each other on the graph, "distorting" the linear sense of time that the "last hour/day/week" headings imply.

Would it be possible to add a configuration option to allow for blank spaces to appear in the graphs' x-axis?

**Comment by xan-m** [comment]
Time-based graphing is not an option with the graphing library I'm using, nor with any of the available graphing libraries I've seen. I think my only option is to roll my own graphing system or heavily modify an existing one. I don't feel very well equipped to take either of those on at the moment, so I'm afraid the graphing is going to stay as it is for now.

Hopefully the more graph time range controls are helpful for now.
