### ISSUE TITLE
Can you publish it?

### ISSUE THREAD

**Issue by ocdtrekkie** [InfiniTimeOrg/InfiniLink#62]
I 100% understand no longer having time to work on an open source project: I and I'm sure many others deeply appreciate the hard work you've invested so far. Obviously my hope is someone will take over the project in due time, but I was wondering if it would be possible for you to finalize publishing the app, so that we do not lose it in 90 days due to TestFlight. In my case, InfiniLink is the only way I can easily update/interact with my PineTime.

**Comment by wandering-hacker** [comment]
Here's the situation as I understand it: Apple requires developers to buy a 'licence' in order to publish to the app store, probably to cut down on spam. This is, I think, the main reason that @xan-m has elected to keep this app in Testflight is that license cost. I myself have not had a lot of time recently to advance myself up the BLE learning curve; indeed, I have never worked on an iOS app before. This said, I hope to make time in the coming few months and get myself to the point at which I will be able to pick up some of the slack and give some back to everyone who has worked so hard on this software already.

**Comment by wandering-hacker** [comment]
I think it may have to do with license payments, although it seems that xan-m has already purchased one. 
I myself have not had a lot of time recently to advance myself up the BLE learning curve; indeed, I have never worked on an iOS app before either. This said, I hope to make time in the coming few months and get myself to the point at which I will be able to pick up some of the slack and give some back to everyone who has worked so hard on this software already.

**Comment by xan-m** [comment]
I did purchase an Apple developer license, which will expire in early August or late September sometime. When that license expires, the published app will no longer be available either. I can push another release in 90 days to keep the beta from expiring, but I’m hoping someone will want to take over the App Store side of things as well, and I’ll leave it to them if they want to publish officially or not.

**Comment by ocdtrekkie** [comment]
Ah yeah, it'd suck to be paying a yearly cost on something you're no longer working on. (Ah, the wonders of the Apple ecosystem...) Have you reached out to the InfiniTime org about this? They may be able to amplify the request for someone to support the iOS side of things.

**Comment by xan-m** [comment]
Yep, I am talking with JF currently about moving the project over to InfiniTimeOrg/Pine64 ownership before my Apple dev account expires, and if all goes well this should be a pretty seamless transition for users!

**Comment by ocdtrekkie** [comment]
That's great to hear!

**Comment by tnlogy** [comment]
Great to hear! Got the watch yesterday and was greeted with the testflight message :) :). 

Maybe someone else is interested in using Pythonista with your PineTime? I made a small test getting step/heart/raw motion data using it. Seems to work fine https://gist.github.com/tnlogy/eb7a958d9216f335d117d85b5402da3b

**Comment by aafishman** [comment]
Looks like the beta TestFlight link may not be active anymore? Any chance if re instating it for the moment, prior to moving ownership?

**Comment by xan-m** [comment]
My mistake, I accidentally deleted the last character of the link when I was removing the text below before transferring to InfiniTimeOrg. It's working on my phone now, can you test and confirm?

**Comment by aafishman** [comment]
Yes! Working now, thanks!

**Comment by jorp** [comment]
So what does the future look like for this app? I see that it's under the org now.

**Comment by xan-m** [comment]
Yep, transferred it to the org and am still maintaining it for now until someone adopts it. My app store license expires in the late summer, so I'll keep it in test flight until then. I've been talking with some people about transferring the app store ownership as well, but nothing is set in stone yet.

**Comment by jorp** [comment]
> Yep, transferred it to the org and am still maintaining it for now until someone adopts it. My app store license expires in the late summer, so I'll keep it in test flight until then. I've been talking with some people about transferring the app store ownership as well, but nothing is set in stone yet.

Thanks for that. Really appreciate you keeping it afloat until then.

Would it maybe be possible to rename this issue and use this for tracking/discussion about the hand over?

--- 
I've been doing some minimal research around this, but does InfiniTime or Pine64 have a backing/tangential nonprofit standing? If so, they can apply to [waive the fee](https://developer.apple.com/support/membership-fee-waiver/) and hold the license necessary.

**Comment by xan-m** [comment]
InfiniLink is being published to the App Store as I type this! My submission was accepted just now and it could take up to 24 hours to be available for download.

I am working on transferring the app to Pine64's new Apple Developer account. FYI, part of that process is that I need to disable TestFlight and kick everyone out of the beta, so be sure to grab the published version once it's available. I'll make announcements in all the usual locations when it's done.

Marking this for closure now, as the app is published.
