### ISSUE TITLE
Can't rename device after renamed once

### ISSUE THREAD

**Issue by Nunya-9018** [InfiniTimeOrg/InfiniLink#69]
I renamed my watch something dumb because I didn't think it would work but now I can change it back

**Comment by Nunya-9018** [comment]
@xan-m

**Comment by xan-m** [comment]
Hey @Nunya-9018. I am no longer maintaining or developing this app. Please don’t tag me 24 hours after opening issues.

Device names are not persistent between installs, so just delete the app and reinstall to fix.

**Comment by Nunya-9018** [comment]
Sorry and thanks
