### ISSUE TITLE
What is the current state of getting iOS notifications, and third-party music apps to work?

### ISSUE THREAD

**Issue by K4LCIFER** [InfiniTimeOrg/InfiniLink#71]
I'd love to be able to control music on my phone from my pinetime, as well as receive my phones notifications on it, so I'm just curious what the state of getting this working is.

**Comment by xan-m** [comment]
Notifications: https://github.com/scandinave/InfiniTime/pull/1

Music controls for 3rd party apps requires Apple Media Service to be implemented in InfiniTime. As far as I know, nobody is working on that. Here’s the spec: https://developer.apple.com/library/archive/documentation/CoreBluetooth/Reference/AppleMediaService_Reference/Specification/Specification.html

**Comment by ItzSwirlz** [comment]
For notifications could it do this? https://developer.apple.com/forums/thread/14484 We already can send a message to the watch (the iOS Connected) message. It would just be waiting for an iOS notification to send through

Also: My TestFlight expires in 7 days, is it possible the new UI can be pushed in a new release soon?

**Comment by ocdtrekkie** [comment]
> Also: My TestFlight expires in 7 days, is it possible the new UI can be pushed in a new release soon?

The new UI is live, it's not on TestFlight. Install the actual app store version.

**Comment by liamcharger** [comment]
I'm going to go ahead and close this issue now due to inactivity and the current state of iOS notifications and system-wide media control.

**Comment by liamcharger** [comment]
For anyone not aware: ANCS has been implemented in [#2217](https://github.com/InfiniTimeOrg/InfiniTime/pull/2217), and AMS is in development!
