### ISSUE TITLE
Can't connect to device

### ISSUE THREAD

**Issue by espro1** [InfiniTimeOrg/InfiniLink#74]
Firmware 1.2

I get the following error message when I try to connect to PineTime:

`Could not connect to device not named 'InfiniTime'. Device name: XYZAB`

I used InfiniLink without any issue when it was still in beta. I hadn't checked it in months when I saw that it was available in the App Store only, so I downloaded it there.

I'm also positive I was running much more recent firmware on my device but it seems to have automatically reverted to v1.2.

I know the app isn't maintained anymore but I was wondering if there is some easy fix.

**Comment by ocdtrekkie** [comment]
Not sure about connecting with firmware that old. But for future reference: There's a "validate firmware" setting on the watch itself. I think if you don't select it, it doesn't save the firmware updates through power loss and stuff.

**Comment by espro1** [comment]
Thanks, I'll look into other options for updating the firmware. I could've swore I 'validated' other versions of the watch but maybe not.
