### ISSUE TITLE
Current firmware update (1.11) hangs

### ISSUE THREAD

**Issue by aafishman** [InfiniTimeOrg/InfiniLink#81]
Looks like there might be an open PR to update the upstream repo branch - regardless at least a few users are unable to make the latest firmware update as the update just hangs and eventually reports the 'is it a zip' message

**Comment by wantyapps** [comment]
I have the same issue, looked at the logs :`Oct 18, 22:21 - Error loading firmware file. Is the file a DFU zip?`. I am guessing it's an error with the build, maybe something with the metadata?

**Comment by devinhenkel** [comment]
I think it's that the top-level branch switched from "master" to "main", but the code is still trying to pull "master". Not sure, but I thought I saw an edit making that update.

**Comment by wantyapps** [comment]
I think you are right! Let's put up an issue on the repo

**Comment by xan-m** [comment]
Hello all — I have merged the pull request, but have run into an issue building the app now that the app has been transferred to Pine64’s App Store Developer account. I’ve reached out to them to sort this out and will get a build pushed out ASAP.

**Comment by wantyapps** [comment]
Thank you!! Have a nice day, good GitHub user! :)

**Comment by xan-m** [comment]
Pushed out an update that should resolve this issue. Please update your app and confirm. 

I’m going to close this out, but please feel free to reopen if it still doesn’t work.

**Comment by GeckoEidechse** [comment]
Successfully updated my PineTime from InfiniTime `1.10` to `1.11` with the newest version of InfiniLink (`1.0.2`) :D
