### ISSUE TITLE
support external resources

### ISSUE THREAD

**Issue by TheAwesome98-Real** [InfiniTimeOrg/InfiniLink#83]
as of infinitime 1.11.0, some features require you to upload external resources to the watch. most other companion apps have this, and infinilink would benefit from it too.

**Comment by wantyapps** [comment]
Hey everyone, any new updates?

**Comment by TheAwesome98-Real** [comment]
lead dev doesn't work on it anymore iirc

**Comment by wantyapps** [comment]
Oh, thanks for the info. Good night 😊

**Comment by Xorger** [comment]
Any updates from the new maintainer? It's been over a year since infinitime 1.11.0.

**Comment by liamcharger** [comment]
I'm going to close this issue now because uploading external resources have been implemented.
