### ISSUE TITLE
App defaults to Russian?

### ISSUE THREAD

**Issue by AeneasChristodoulou** [InfiniTimeOrg/InfiniLink#85]
Hey guys, I just installed the App, but it immediately defaulted to Russian. My Russian is pretty bad, and I couldn't find a setting for how to change the language. Uninstalling and reinstalling the App didn't help me so far. Any Ideas?

**Comment by AeneasChristodoulou** [comment]
Able to fix it by removing the russian keyboard (keyboard number 4 out of 5, german AND english being above it in order).
Is there a way to make it changeable by the user? Or would that be something that needs to be implemented first? Sadly I don't have any SWIFT Knowledge really, as I mainly do python.

**Comment by poormusic2001** [comment]
Hi, there is an option which is named PREFERRED LANGUAGES in the Language & Region of the General the setting in iOS system. If the first is Russian, then the App will use it as default.
![327BB870-78FE-4AF3-BFA3-1C0C628105BC](https://user-images.githubusercontent.com/10296589/211158970-66843613-6787-491d-a6c0-48c435f39bfa.png)
