### ISSUE TITLE
Send push notification on low watch battery

### ISSUE THREAD

**Issue by GeckoEidechse** [InfiniTimeOrg/InfiniLink#87]
The battery notification on the PineTime is rather easy to miss and naturally, if you don't have your watch on you while you receive one, you'll miss it.

As such it would be nice if we could additionally enable receiving a push notification on the paired iPhone. Even when missing the initial notification, you'll still see it in your notification center so it's a nice reminder to charge your watch when it's low. ^^

**Comment by liamcharger** [comment]
Hello, I just implemented this in the new-ui branch! Feel free to test it out and give me feedback!

**Comment by GeckoEidechse** [comment]
That's awesome, thanks :D

I assume for testing, I'd have to checkout `new-ui` locally, compile myself, and load onto an iOS device?
In which case I unfortunately won't be able to do so, due to not having access to a Mac to compile the code and load onto an iOS device :/
Looking forward to the release though <3

**Comment by liamcharger** [comment]
Yes, you would have to compile it and install it on your device. I'll try to push an update as soon as possible though :)
