### ISSUE TITLE
Monthly overview of step count having wrong day indicator

### ISSUE THREAD

**Issue by GeckoEidechse** [InfiniTimeOrg/InfiniLink#89]
For the monthly overview the weekdays on top of the calender don't seem to update according to the first day of week.

Instead they appear to always start on _Sunday_ regardless of iOS setting. This results in the days of the calender being arranged "correctly", for example in the screenshot below, April 1st which is a Saturday is the second to last entry in that row, but the day indicator above says F(riday).

![image](https://user-images.githubusercontent.com/40122905/229362460-c7e44cc7-37f9-40cb-8dd8-d93d80013f01.png)

Somewhat related to #88

**Comment by liamcharger** [comment]
Yes, the monthly overview wasn't well developed, I think I'll try to reimplement it soon, but it's not a high priority right now.

**Comment by liamcharger** [comment]
I closed this issue because I removed the monthly overview until I reimplement it in later commits.
