### ISSUE TITLE
Time does not sync to watches running InfiniTime 1.12

### ISSUE THREAD

**Issue by mkincaid** [InfiniTimeOrg/InfiniLink#90]
In current InfiniLink (1.0.2), the current time is not successfully written if the watch is running the new InfiniTime 1.12 release. This worked in InfiniTime <= 1.11, but according to InfiniTime devs, this is actually caused by a bug in companion apps.

See https://github.com/InfiniTimeOrg/InfiniTime/issues/1724 in InfiniTime: "Amazfish is most likely writing a byte or two too few to the Current Time Service and thus they get ignored. The service was updated to be more standards-compliant."

**Comment by abumalick** [comment]
I got this actually after updating to last firmware. I had to manually set the date and time.
