### ISSUE TITLE
InfiniLink for iOS can't connect

### ISSUE THREAD

**Issue by Romeo264** [InfiniTimeOrg/InfiniLink#91]
It is stuck in the "connecting" mode

**Comment by sanderhollaar** [comment]
Workaround: delete Infinilink from Iphone (not sure if needed), reboot PineTime by holding the button for eight seconds.

Pairing now succeeds.

**Comment by sanderhollaar** [comment]
Cannot connect to pinetime, search issues, find own comment with workaround :facepalm:

**Comment by Romeo264** [comment]
Thank you that fixed it!

**Comment by ocdtrekkie** [comment]
@sanderhollaar I didn't need to remove the app, just rebooting the PineTime fixed it for me.

...Daylight Savings Time.
