### ISSUE TITLE
Handle music playing differently

### ISSUE THREAD

**Issue by x-industries-uk** [InfiniTimeOrg/InfiniLink#94]
On my PineTime, there is an app to control the music on my phone. Handy, right? Well, only if you use the official Music app.

In order to sync my music with my Linux machines, I use foobar2000 to play music on my phone, and my PineTime doesn't work with it.

I would suggest making the app interact with the iOS Media Player Framework, rather than with "iTunes & Apple Music".

**Comment by liamcharger** [comment]
This would require Apple Media Services to be implemented in InfiniTime, not the InfiniLink app. It's currently not possible to achieve notifications and system wide media control without integrating the services into InfiniTime first.

**Comment by x-industries-uk** [comment]
Ah, well, I guess that's Apple for you. Thanks anyway!

(I'll leave this open, though, in case anybody has a stroke of genius)
