### ISSUE TITLE
Heart Rate Display Not Working

### ISSUE THREAD

**Issue by Romeo264** [InfiniTimeOrg/InfiniLink#96]
Downloaded the new version and the Heart Rate Display doesn't work. It worked in previous versions. Why doesn't it work in this one?

**Comment by liamcharger** [comment]
Hello! Could you please elaborate on the issue you're experiencing? Are you experiencing the issue on an instance of the app that you built from source, or is this from the App Store?

**Comment by Romeo264** [comment]
It's from the App Store. After updating to 1.13 the Heart Rate option no longer works and gives me an alert of Insufficient Heart Data. ![image](https://github.com/InfiniTimeOrg/InfiniLink/assets/82793364/d0b5fdde-38d2-4187-bb26-6fbc975cd36d)

**Comment by liamcharger** [comment]
Hmm, I don't know if there's much I can do, make sure your PineTime is connected and actively monitoring your heart rate so that it's streaming data to the app.

**Comment by Romeo264** [comment]
After you said make sure to have it connected to the pinetime it began to work. Turned on the heart option and my goodness it worked. Thanks

**Comment by liamcharger** [comment]
No problem! Glad I could help!
